// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoFQEqmbo8m98LtW7gdg4LhZqer-qxT0M',
    appId: '1:1011380059267:web:b3994f3c464365a6916fb6',
    messagingSenderId: '1011380059267',
    projectId: 'shinydeal-14d76',
    authDomain: 'shinydeal-14d76.firebaseapp.com',
    storageBucket: 'shinydeal-14d76.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2h3PJ5SOuBI5wvJOcPbK_kmrBeCRXelM',
    appId: '1:1011380059267:android:d8741aa9e7c6cb2f916fb6',
    messagingSenderId: '1011380059267',
    projectId: 'shinydeal-14d76',
    storageBucket: 'shinydeal-14d76.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu3hJa2FIRYXty2v87TtBvYb_8txlmZ0g',
    appId: '1:1011380059267:ios:bbbd38e82fce6bb9916fb6',
    messagingSenderId: '1011380059267',
    projectId: 'shinydeal-14d76',
    storageBucket: 'shinydeal-14d76.appspot.com',
    iosBundleId: 'com.example.menetrendApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCu3hJa2FIRYXty2v87TtBvYb_8txlmZ0g',
    appId: '1:1011380059267:ios:768e2e097ebb6a8d916fb6',
    messagingSenderId: '1011380059267',
    projectId: 'shinydeal-14d76',
    storageBucket: 'shinydeal-14d76.appspot.com',
    iosBundleId: 'com.example.menetrendApp.RunnerTests',
  );
}
